#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

struct Territorio {
    char nome[30];
        char cor[10];
            int tropas;
            };

            void cadastrar(struct Territorio *t);
            void exibirMapa(struct Territorio *t);
            void atacar(struct Territorio *atacante, struct Territorio *defensor);

            int main() {
                srand(time(NULL));

                    int tamanho = 5; 
                        struct Territorio *t = malloc(tamanho * sizeof(struct Territorio));

                            if (t == NULL) {
                                    printf("Erro ao alocar memoria.\n");
                                            return 1;
                                                }

                                                    cadastrar(t);

                                                        while (1) {
                                                                int a, d;
                                                                        printf("\n================================");
                                                                                printf("\n   MAPA MUNDI - ESTADO ATUAL\n");
                                                                                        printf("================================\n\n");
                                                                                                exibirMapa(t);

                                                                                                        printf("\n--- FASE DE ATAQUE ---");

                                                                                                                printf("\nEscolha o número do território ATACANTE (ou 0 para sair): ");
                                                                                                                        scanf("%d", &a);
                                                                                                                                if (a == 0) break;

                                                                                                                                        printf("Escolha o número do território DEFENSOR (1 a 5): ");
                                                                                                                                                scanf("%d", &d);

                                                                                                                                                        // Ajustando para índice correto (1 a 5 → 0 a 4)
                                                                                                                                                                a -= 1;
                                                                                                                                                                        d -= 1;

                                                                                                                                                                                if (a < 0 || a >= tamanho || d < 0 || d >= tamanho) {
                                                                                                                                                                                            printf("Indice invalido.\n");
                                                                                                                                                                                                        continue;
                                                                                                                                                                                                                }

                                                                                                                                                                                                                        if (a == d) {
                                                                                                                                                                                                                                    printf("Nao pode atacar o mesmo territorio.\n");
                                                                                                                                                                                                                                                continue;
                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                atacar(&t[a], &t[d]);
                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                        free(t);
                                                                                                                                                                                                                                                                            printf("\nMemoria liberada. Programa encerrado.\n");
                                                                                                                                                                                                                                                                                return 0;
                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                void cadastrar(struct Territorio *t) {
                                                                                                                                                                                                                                                                                    int i;
                                                                                                                                                                                                                                                                                        for (i = 0; i < 5; i++) {
                                                                                                                                                                                                                                                                                                printf("\n--- Cadastrando Territorio %d ---\n", i + 1);

                                                                                                                                                                                                                                                                                                        printf("Nome: ");
                                                                                                                                                                                                                                                                                                                scanf("%s", t[i].nome);

                                                                                                                                                                                                                                                                                                                        printf("Cor: ");
                                                                                                                                                                                                                                                                                                                                scanf("%s", t[i].cor);

                                                                                                                                                                                                                                                                                                                                        printf("Tropas: ");
                                                                                                                                                                                                                                                                                                                                                scanf("%d", &t[i].tropas);
                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                    void exibirMapa(struct Territorio *t) {
                                                                                                                                                                                                                                                                                                                                                        int i;
                                                                                                                                                                                                                                                                                                                                                            for (i = 0; i < 5; i++) {
                                                                                                                                                                                                                                                                                                                                                                    printf("[%d] %s (Exercito %s, Tropas: %d)\n",
                                                                                                                                                                                                                                                                                                                                                                                    i + 1, t[i].nome, t[i].cor, t[i].tropas);
                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                        void atacar(struct Territorio *atac, struct Territorio *def) {

                                                                                                                                                                                                                                                                                                                                                                                            printf("\n====== RESULTADO DA BATALHA ======\n");

                                                                                                                                                                                                                                                                                                                                                                                                int dadoA = (rand() % 6) + 1;
                                                                                                                                                                                                                                                                                                                                                                                                    int dadoD = (rand() % 6) + 1;

                                                                                                                                                                                                                                                                                                                                                                                                        printf("O Atacante %s rolou o dado e tirou: %d\n", atac->nome, dadoA);
                                                                                                                                                                                                                                                                                                                                                                                                            printf("O Defensor %s rolou o dado e tirou: %d\n", def->nome, dadoD);

                                                                                                                                                                                                                                                                                                                                                                                                                int poderA = atac->tropas + dadoA;
                                                                                                                                                                                                                                                                                                                                                                                                                    int poderD = def->tropas + dadoD;

                                                                                                                                                                                                                                                                                                                                                                                                                        if (poderA > poderD) {
                                                                                                                                                                                                                                                                                                                                                                                                                                printf("\nVitória do Atacante!\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("%s perdeu 1 tropa.\n", def->nome);

                                                                                                                                                                                                                                                                                                                                                                                                                                                def->tropas -= 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (def->tropas < 0) def->tropas = 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (def->tropas == 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("%s conquistou o território %s!\n", atac->cor, def->nome);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        strcpy(def->cor, atac->cor);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def->tropas = 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                atac->tropas -= 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else if (poderA < poderD) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("\nO Defensor resistiu ao ataque!\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("%s perdeu 1 tropa.\n", atac->nome);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    atac->tropas -= 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (atac->tropas < 1) atac->tropas = 1;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("\nEmpate!\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("Ambos os territórios perderam 1 tropa.\n");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        atac->tropas -= 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def->tropas -= 1;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (atac->tropas < 1) atac->tropas = 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (def->tropas < 1) def->tropas = 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    